apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: myspace
      protocol: layer2
      addresses:
      - 192.168.56.240-192.168.56.250
